lb_diff_controller:
  linear:
    x:
      has_velocity_limits: true
      min_velocity: -0.25
      max_velocity: 0.25
      has_acceleration_limits: true
      min_acceleration: -0.5
      max_acceleration: 1.0
      has_jerk_limits: false
  angular:
    z:
      has_velocity_limits: true
      max_velocity: 5
      has_acceleration_limits: false
      has_jerk_limits: false